image: node:latest

cache:
  paths:
    - node_modules/

build:
    tags:
        - spinny
    script:
        - npm install

unit_test:
    tags:
        - spinny
    script:
        - npm run test
    dependencies:
        - build