image: node:latest

variables:
    GIT_CLEAN_FLAGS: none

stages:
    - build
    - test
    - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
    stage: build
    tags:
        - docker
    script:
        - npm install

unit_tests:
    stage: test
    tags:
        - docker
    script:
        - npm run test
    dependencies:
        - install_dependencies

production:
    stage: deploy
    tags:
        - droplet
    script:
        - pwd
        - ls
        - cd /home/alexiscrack3/spinny-api
        - dockerd
        - /usr/local/bin/docker-compose down
        - git checkout develop
        - git pull
        - /usr/local/bin/docker-compose up -d
