image: node:latest

stages:
    - build
    - test
    - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
    stage: build
    tags:
        - spinny
    script:
        - npm install

unit_tests:
    stage: test
    tags:
        - spinny
    script:
        - npm run test
    dependencies:
        - install_dependencies

production:
    stage: deploy
    tags:
        - spinny
    script:
        - pwd
        - ls
        - cd ~/spinny-api
        - ls
        - sudo docker-compose down
        - git checkout develop
        - git pull
        - sudo docker-compose up -d
