version: "3"

services: 
    api:
        image: "alexiscrack3/spinny-api:latest"
        env_file: .env
        environment: 
            MONGO_HOSTNAME: db
            MONGO_PORT: $MONGO_PORT
            MONGO_DB: $MONGO_DB
        depends_on: 
            - db
        ports: 
            - "3000:3000"
            # - "3000-3010:3000"
    db:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - dbdata:/data/db

volumes:
  dbdata:
