version: "3"

services:
    api:
        container_name: api
        env_file: .env
        environment:
            MONGO_HOSTNAME: db
            MONGO_PORT: $MONGO_PORT
            MONGO_DB: $MONGO_DB
        depends_on:
            - db
        ports:
            - "3000:3000"
            # - "3000-3010:3000"
        networks:
            - custom-network
    db:
        image: mongo
        container_name: db
        ports:
            - "27017:27017"
        networks:
            - custom-network
        volumes:
            - dbdata:/data/db
    web:
        image: alexiscrack3/spinny-react:latest
        container_name: web
        environment:
            API_URL: api
        depends_on:
            - api
        ports:
            - "80:8080"
        networks:
            - custom-network

networks:
    custom-network:
        driver: bridge

volumes:
  dbdata:
