version: "3"

services: 
    api:
        build: .
        container_name: api
        environment: 
            DB_HOST: "db"
        depends_on: 
            - db
        ports: 
            - "80:3000"
            # - "3000-3010:3000"
        networks:
            - custom-network
    db:
        image: mongo
        container_name: db
        networks:
            - custom-network

networks:
    custom-network:
        driver: bridge
