version: "3"

services: 
    api:
        build: .
        container_name: api
        environment: 
            MONGO_HOSTNAME: "db"
        depends_on: 
            - db
        ports: 
            - "80:3000"
            # - "3000-3010:3000"
        networks:
            - custom-network
    db:
        image: mongo
        container_name: db
        networks:
            - custom-network
        volumes:
            - dbdata:/data/db

networks:
    custom-network:
        driver: bridge

volumes:
  dbdata:
